### ISSUE TITLE
ssllabs plugin issue on 1.2.8p18 CEE

### ISSUE THREAD

**Issue by tgm4883** [lgbff/lgb_check_mk_plugins#11]
I'm trying to run this on 1.2.8p18 CEE. I've got it installed and can configure it, however when I configure it to run on one of my check_mk servers, it prevents all other services from being returned so it appears that the server only has a ping check.

**Comment by seppovic** [comment]
Hey tgm4883, 
as ssllabs plugin gets its data by acting as a "datasource program" (similiar to snmp checks etc.) you have to configure check_mk agent to be used as well, from my understanding this is only possible with tags and auxillary tags. (but i may be wrong) here is at least how i add ssllabs plugin to a host that also needs to be monitored by check_mk agent:

1. create an aux tag e.g. "ssllabs", "monitor ssllabs grade"
2. modify "Agent type" tag group and add an item like "ssllabs-tcp", "Dual: check_mk agent & ssllabs", select "monitor ssllabs grade" and "monitor via check_mk Agent"
3. create a rule "Datasource Programs" -> "Check SSL Server via ssllabs API" -> specify the parameters and the conditions
4. configure your host to use the newly created Agenttype.

it might be easier to create a new host for only the ssllabs grade check, which makes sense if you use some sort of loadbalancing of your website.

cheers

**Comment by tgm4883** [comment]
I'm not sure this is the problem I'm having, but I've just created a new host in order to test this. I've got it setup just as you've posted. I've installed ssllabs 1.3.1. When I look at the services discovered, I see http://imgur.com/2th8VE1

Going into diagnostic mode, I see the ssllabs grade in the agent output, but that's it
http://imgur.com/2HPKy9i

**Comment by tgm4883** [comment]
Doing some debugging on the inventory check for this and it doesn't appear that it has any inventory, which is odd considering the ssllabs_grade in the diagnostic check.

**Comment by tgm4883** [comment]
I'm probably just unfamiliar with how these types of checks work, I've now tried copying the special agent_ssllabs file down to /usr/lib/check_mk_agent/plugins/ and still nothing.

**Comment by tgm4883** [comment]
Hmm, still can't figure this out. I've configured the check on it's own server rather than one of my check_mk servers and I see the result when I view the tests on the server. Should the check be showing up under the host in the interface or somewhere else?

**Comment by tgm4883** [comment]
Did some additional digging, if I create a new site this seems to work fine. What could be restricting this from working in my regular site?
