### ISSUE TITLE
Internal error after upgrade from 1.2.8p23 to 1.4.0p1

### ISSUE THREAD

**Issue by Managuensis11** [lgbff/lgb_check_mk_plugins#12]
When i remove the .py-files from ~/web/plugins/wato the error is gone.
Does sb know what i have to change? 

![fehler 1](https://user-images.githubusercontent.com/29372567/27029088-2b521b54-4f67-11e7-87ca-64885a5e7198.PNG)
![fehler 2](https://user-images.githubusercontent.com/29372567/27029087-2b4d1c4e-4f67-11e7-8ae5-869794857a14.PNG)

**Comment by seppovic** [comment]
Had the same problem. If i find the time i add a pull request, anyways here is the quick solution. Like the official check parameter filese from:
http://git.mathias-kettner.de/git/?p=check_mk.git;a=blob;f=web/plugins/wato/check_parameters.py;hb=refs/heads/1.4.0
> 1402                     elements = [
> 1403                         RegExpUnicode(
> 1404                             title = _("Include Pattern"),
> 1405                             mode = RegExp.prefix,
> 1406                         ),

i added the `mode = RegExp.prefix,` line to the ssllabs_check_parameters.py wato file.

**Comment by Managuensis11** [comment]
Where did you add the refferd line in the ssllabs_check_parameters.py file?
In my case it doen't seem to work.

**Comment by lgbff** [comment]
Pls wait, we change in the moment our environment to cmk version 1.4
After the tests, i can deploy the new mkp.

**Comment by lgbff** [comment]
I upload the new version to mk https://mathias-kettner.de/check_mk_exchange_file.php?HTML=yes&file=ssllabs-1.4.1.mkp
