### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by m3rlinux** [lgbff/lgb_check_mk_plugins#13]
Hi! I found some little bugs in your lvs plugin.
1. you writed in README: "Install the lvsgsp binary on /usr/local/sbin"
but the agent (lvs script) searchs binary "lvsgsp" in /usr/local/bin;
2. (not really bug) the installation of package put the plugin under "/opt/omd/versions/$version/**local**/share/check_mk/agents/plugins/lvs"
But if you want to show it in check_mk WATO interface under "Monitoring Agent" link, you have tu strip out "local" from above path.
Then is better to put as First comment something shorter like "# LVS plugin", because it is showed as "link description".
3. The plugin does not work properly due to a sintax error on line 68: 
I changed it with:
infotext = str(worst_state) + " - " + ', '.join(info_list)
and now it seems to work.

Thats all for now ;)

**Comment by schoekek** [comment]
I uploaded a new mk package @mkexchange. This contain lvsgsp binary not anymore. I will update the repo asap ;-)
Thx for your contribution.
