### ISSUE TITLE
ssllabs api check not current in repo

### ISSUE THREAD

**Issue by moschlar** [lgbff/lgb_check_mk_plugins#17]
Hi,

I noticed that the version of the [ssllabs plugin on the Checkmk Exchange](https://exchange.checkmk.com/p/ssllabs) is newer than the one in this repo.
Would you mind uploading it here?

Regards,
Moritz

**Comment by schoekek** [comment]
the latest version is allways on exchange....

**Comment by moschlar** [comment]
@schoekek If you could update your code here in the Git repo, I could send you my improvements that I had to edit for Checkmk 2.2!

**Comment by schoekek** [comment]
I will update to version 2.2 in the next few weeks, and then there will also be a new mkp.
