### ISSUE TITLE
ssllabs-mkp - Not working with Checkmk 2.0

### ISSUE THREAD

**Issue by FJerusalem** [lgbff/lgb_check_mk_plugins#18]
As topic implies - current check is not working with Checkmk 2.0:

File "/omd/sites/mysite/local/share/check_mk/agents/special/agent_ssllabs", line 19, in <module>
from cmk.utils.paths import tmp_dir
ImportError: No module named cmk.utils.pathsCRIT
ignored: systemtime: System Time

**Comment by schoekek** [comment]
i am currently in the process of switching to 2.0....

**Comment by schoekek** [comment]
pls use the latet version https://exchange.checkmk.com/p/ssllabs
