### ISSUE TITLE
Not possible to have more than one SSLLabs check from one machine

### ISSUE THREAD

**Issue by 47k** [lgbff/lgb_check_mk_plugins#19]
Hello 

I have some servers with more than one website on it (and of course, different ssl certificates). I configured everything, but it appear only the first site I configured. All other sites are not listed/detected. 

Greetz

**Comment by schoekek** [comment]
I also have a lot of SSL vHost with different certs here on a server.
I define an extra host in check_mk for each Namebased vHost and assign it to the ssllabs checks.
Therefore the plugin does not support multiple ssl certs on one host.
