### ISSUE TITLE
WARN - reboot required

### ISSUE THREAD

**Issue by txsastre** [lgbff/lgb_check_mk_plugins#2]
I installed it on a proxmox server, its a virtualitzacion system, works on Debian and uses KVM and Qemu (proxmox.org)
the plugin is saying all the time "WARN - reboot required" but I have already rebooted it.

The check_mk client is Agent version 1.2.4p5, and (problably the problem) the kernel of proxmox is Linux px 2.6.32-34-pve x86_64 GNU/Linux

I've just commented this lines in the apt server code
    if (reboot_req == "yes") and (level == 0):
        level = 1
        msg = "reboot required (!)"

now it works fine, but some bug is there.

**Comment by lgbff** [comment]
I have no proxmox Installation to testing.
Pls check the output of apt agent plugin, change the plugincode and send a merge request to fix it on promox.

Deaktivate on check_mk server check ist not the rigth way, ist disable the update check on all Clients ;-(
