### ISSUE TITLE
Bug in check file, APT service reports Debian Version 0.0 and all updates done if apt plugin isn't available

### ISSUE THREAD

**Issue by dasmarci** [lgbff/lgb_check_mk_plugins#4]
Hi Karsten,

following situation:

* added apt-2.7
* "manual checks -> apt" for all debian hosts
* activate changes

...APT services are shown for all debian hosts like expected. Now some times later delete the plugin from one debian host...

The APT service will show something like "Debian 0.0, all updates done" (I do not know the exact wording).

The issue can be found in the check file. Here the check is done even if no info is provided (no <<<apt>>> section.

Working patch:
<pre><code>
`45,51c45,52
<     apt_upgrades = {}
<     level        = 0
<     msg          = ""
<     updates      = 0
<     crit_updates = 0
<     deb_release  = 0.0
<     reboot_req   = "no"
---
>     if info:
>         apt_upgrades = {}
>         level        = 0
>         msg          = ""
>         updates      = 0
>         crit_updates = 0
>         deb_release  = 0.0
>         reboot_req   = "no"
53,56c54,57
<     # Parse the agent output
<     if len(info) > 0:
<         deb_release  = info[1][0]
<         reboot_req   = info[0][0]
---
>         # Parse the agent output
>         if len(info) > 0:
>             deb_release  = info[1][0]
>             reboot_req   = info[0][0]
58,59c59,60
<     if len(info) > 2:
<         packages  = info[2:]
---
>         if len(info) > 2:
>             packages  = info[2:]
61,68c62,69
<         for package in packages:
<             name   = package[0]
<             updates += 1
<             source = package[1].split(' ')[0].split(':')[0]
<             if source in apt_repository_severity:
<                 severity  = apt_repository_severity[source]
<             else:
<                 severity  = apt_repository_severity['__default__']
---
>             for package in packages:
>                 name   = package[0]
>                 updates += 1
>                 source = package[1].split(' ')[0].split(':')[0]
>                 if source in apt_repository_severity:
>                     severity  = apt_repository_severity[source]
>                 else:
>                     severity  = apt_repository_severity['__default__']
70,71c71,72
<             if severity >= 2:
<                 crit_updates += 1
---
>                 if severity >= 2:
>                     crit_updates += 1
73c74
<             level = max(level, severity)
---
>                 level = max(level, severity)
82,89c83,92
<     if (reboot_req == "yes") and (level == 0):
<         level = 1 
<         msg = "reboot required (!)"
< 
<     if level > 0:
<         return (level, "%s" % msg)
<     else:
<         return (level, "Debian %s all packages are up to date" % deb_release)
---
>         if (reboot_req == "yes") and (level == 0):
>             level = 1 
>             msg = "reboot required (!)"
> 
>         if level > 0:
>             return (level, "%s" % msg)
>         else:
>             return (level, "Debian %s all packages are up to date" % deb_release)
> 
>     return (3, "No apt data found in agent output!")
<\code><\pre>

Regards,
Marcel

**Comment by lgbff** [comment]
pls send me a merge request.

**Comment by dasmarci** [comment]
Pull request created.
